apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: database
  template:
    metadata:
      labels:
        app: guestbook
        tier: database
    spec:
      volumes:                
      - name: postgrestorage
        persistentVolumeClaim:
          claimName: pgdata-claim
      containers:
      - name: postgres
        image: quay.io/fedora/postgresql-16:latest
        ports:
        - containerPort: 5432
        volumeMounts:         
        - name: postgrestorage
          mountPath: /var/lib/pgsql/data
        env:                  
        - name: POSTGRESQL_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRESQL_USER
        - name: POSTGRESQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRESQL_DATABASE
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-password
              key: POSTGRESQL_PASSWORD